export interface Question {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface Module {
  id: string;
  title: string;
  description: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  questions: Question[];
}

export const FINANCE_MODULES: Module[] = [
  {
    id: "dcf",
    title: "Discounted Cash Flow (DCF)",
    description: "Master the art of intrinsic valuation by forecasting free cash flows and determining the appropriate discount rate.",
    difficulty: "Intermediate",
    questions: [
      {
        id: "dcf_1",
        question: "In a DCF analysis, what happens to Enterprise Value if WACC increases, all else equal?",
        options: ["Enterprise Value increases", "Enterprise Value decreases", "Enterprise Value remains unchanged", "Enterprise Value becomes zero"],
        correctIndex: 1,
        explanation: "WACC is the discount rate applied to future cash flows. A higher WACC reduces the present value of those cash flows, lowering Enterprise Value.",
      },
      {
        id: "dcf_2",
        question: "Which method for calculating Terminal Value assumes the business grows at a constant rate in perpetuity?",
        options: ["Exit Multiple Method", "Gordon Growth Model", "Liquidation Value Method", "Book Value Method"],
        correctIndex: 1,
        explanation: "The Gordon Growth Model (Perpetuity Growth) calculates Terminal Value as FCF × (1 + g) / (WACC − g), assuming constant perpetual growth.",
      },
      {
        id: "dcf_3",
        question: "Free Cash Flow to Firm (FCFF) is calculated before paying which of the following?",
        options: ["Taxes", "Debt holders and equity holders", "Operating expenses", "Depreciation"],
        correctIndex: 1,
        explanation: "FCFF is the cash available to all capital providers — both debt and equity — before any financing payments are made.",
      },
      {
        id: "dcf_4",
        question: "Which of the following is added back to Net Income when calculating Unlevered Free Cash Flow?",
        options: ["Interest expense (after-tax)", "Dividends paid", "Capital expenditures", "Revenue growth"],
        correctIndex: 0,
        explanation: "Since UFCF is pre-debt, after-tax interest expense is added back to Net Income to eliminate the effect of financing structure.",
      },
      {
        id: "dcf_5",
        question: "The terminal value in a 5-year DCF typically represents what proportion of total Enterprise Value?",
        options: ["10–20%", "30–50%", "60–80%", "95–100%"],
        correctIndex: 2,
        explanation: "In practice, terminal value often accounts for 60–80% (sometimes more) of total DCF value, highlighting its sensitivity and importance.",
      },
      {
        id: "dcf_6",
        question: "What does the equity risk premium (ERP) represent in the CAPM formula?",
        options: ["The risk-free rate of return", "Extra return investors demand for holding equities over risk-free assets", "The company's beta", "The cost of debt"],
        correctIndex: 1,
        explanation: "ERP is the expected market return minus the risk-free rate. It compensates investors for taking on the additional risk of equity markets.",
      },
      {
        id: "dcf_7",
        question: "If a company's beta is 1.5 and the market risk premium is 6%, what is the additional return above the risk-free rate per CAPM?",
        options: ["6%", "7.5%", "9%", "1.5%"],
        correctIndex: 2,
        explanation: "CAPM additional return = Beta × ERP = 1.5 × 6% = 9%. This is added to the risk-free rate to get cost of equity.",
      },
      {
        id: "dcf_8",
        question: "In a DCF, CapEx is treated as:",
        options: ["An add-back because it is non-cash", "A deduction because it represents cash outflow", "Irrelevant to free cash flow", "Added to EBITDA to get EBIT"],
        correctIndex: 1,
        explanation: "Capital expenditures are real cash outflows. They reduce Free Cash Flow even though they may be capitalized on the balance sheet.",
      },
      {
        id: "dcf_9",
        question: "Which rate is typically used as the risk-free rate in US DCF analyses?",
        options: ["Federal Funds Rate", "10-Year US Treasury yield", "SOFR", "Prime Rate"],
        correctIndex: 1,
        explanation: "The 10-Year US Treasury yield is the standard proxy for the risk-free rate in US DCF models, as it reflects long-term default-free borrowing costs.",
      },
      {
        id: "dcf_10",
        question: "What is the purpose of a sensitivity table in a DCF model?",
        options: ["To compute WACC precisely", "To show how Enterprise Value changes under different WACC and growth rate assumptions", "To project revenue", "To calculate depreciation schedules"],
        correctIndex: 1,
        explanation: "Sensitivity tables (data tables) illustrate how the output (e.g., EV or share price) varies across a range of key inputs like WACC and terminal growth rate.",
      },
      {
        id: "dcf_11",
        question: "How is Enterprise Value converted to Equity Value in a DCF?",
        options: ["Add net debt and subtract cash", "Subtract net debt (debt minus cash)", "Add preferred stock and minority interest", "Divide by shares outstanding"],
        correctIndex: 1,
        explanation: "Equity Value = Enterprise Value − Net Debt (where Net Debt = total debt − cash). You may also subtract preferred stock and minority interest.",
      },
      {
        id: "dcf_12",
        question: "An increase in net working capital (NWC) has what effect on Free Cash Flow?",
        options: ["Increases FCF", "Decreases FCF", "No effect on FCF", "Doubles FCF"],
        correctIndex: 1,
        explanation: "An increase in NWC means the business is tying up more cash in operations (e.g., higher receivables), which reduces free cash flow.",
      },
      {
        id: "dcf_13",
        question: "What does a higher terminal growth rate assumption do to Enterprise Value?",
        options: ["Decreases it", "Increases it", "Has no effect", "Makes it negative"],
        correctIndex: 1,
        explanation: "A higher terminal growth rate increases the terminal value numerator and compresses the denominator (WACC − g), raising Enterprise Value.",
      },
      {
        id: "dcf_14",
        question: "Which of the following would NOT be included in Free Cash Flow to Equity (FCFE)?",
        options: ["Net income", "Depreciation & amortization add-back", "Interest expense (after-tax)", "Net borrowings"],
        correctIndex: 2,
        explanation: "FCFE is post-debt cash flow. After-tax interest is already embedded in net income; you do not add it back separately as it is not an add-back for FCFE purposes. Net borrowings are included.",
      },
      {
        id: "dcf_15",
        question: "The Exit Multiple Method for terminal value is based on:",
        options: ["Perpetual growth of free cash flows", "Applying a market multiple (e.g., EV/EBITDA) to a final-year metric", "Book value of assets", "Dividend discount model"],
        correctIndex: 1,
        explanation: "The Exit Multiple Method applies a selected market multiple to the projected final-year metric (commonly EBITDA) to estimate the terminal value.",
      },
      {
        id: "dcf_16",
        question: "If a company has no debt, its WACC equals:",
        options: ["Its cost of debt", "Its cost of equity", "Zero", "Its EBITDA margin"],
        correctIndex: 1,
        explanation: "With no debt, the entire capital structure is equity, so WACC = Cost of Equity.",
      },
      {
        id: "dcf_17",
        question: "What does it mean for a DCF to be 'sum-of-the-parts'?",
        options: ["Adding up all assets on the balance sheet", "Valuing each business segment separately and summing them", "Averaging multiple DCF scenarios", "Adding terminal value to year-1 cash flow only"],
        correctIndex: 1,
        explanation: "A SOTP DCF values each division or segment with its own assumptions and discount rate, then sums the parts to get total Enterprise Value.",
      },
      {
        id: "dcf_18",
        question: "In WACC, why is debt cost multiplied by (1 − tax rate)?",
        options: ["Because interest is paid from after-tax profits", "Because interest expense is tax-deductible, providing a tax shield", "Because debt is riskier than equity", "Because it reduces beta"],
        correctIndex: 1,
        explanation: "Interest expense is deductible for tax purposes, so the effective (after-tax) cost of debt is lower than the stated coupon rate.",
      },
      {
        id: "dcf_19",
        question: "Which of the following best defines 'unlevered beta'?",
        options: ["Beta with financial leverage included", "Beta stripped of capital structure effects, reflecting only business risk", "Beta of the overall stock market", "The risk-free rate proxy"],
        correctIndex: 1,
        explanation: "Unlevered (asset) beta removes the effect of financial leverage to isolate operating/business risk, used when re-levering a comparable's beta for a target company.",
      },
      {
        id: "dcf_20",
        question: "What is the typical long-term terminal growth rate assumption for a mature US company?",
        options: ["0–1%", "1–3%", "5–7%", "8–10%"],
        correctIndex: 1,
        explanation: "Most mature companies use a terminal growth rate of 1–3%, roughly in line with long-term GDP growth or inflation, reflecting sustainable perpetual growth.",
      },
      {
        id: "dcf_21",
        question: "If revenue grows but operating margins contract, what likely happens to EBITDA in absolute terms?",
        options: ["It always increases", "It depends on the magnitude of each change", "It always decreases", "It becomes negative"],
        correctIndex: 1,
        explanation: "EBITDA can rise or fall depending on whether revenue growth outpaces the margin compression in absolute dollar terms.",
      },
      {
        id: "dcf_22",
        question: "Which of the following increases FCFF?",
        options: ["Higher CapEx", "Higher D&A (non-cash add-back)", "Higher NWC build", "Higher interest expense"],
        correctIndex: 1,
        explanation: "D&A is a non-cash expense added back to Net Income when computing FCFF, directly increasing free cash flow.",
      },
      {
        id: "dcf_23",
        question: "What is a 'stub period' in a DCF?",
        options: ["A period beyond the explicit forecast horizon", "A partial first year when the valuation date is mid-year", "The final year of the projection", "An extra sensitivity scenario"],
        correctIndex: 1,
        explanation: "A stub period accounts for the fact that a fiscal year may already be partially complete at the valuation date, so only the remaining months are discounted.",
      },
      {
        id: "dcf_24",
        question: "Mid-year discounting convention assumes cash flows are received:",
        options: ["At the end of each year", "At the beginning of each year", "At the middle of each year", "All at once at the terminal year"],
        correctIndex: 2,
        explanation: "Mid-year convention (discount factor of 0.5, 1.5, 2.5 …) assumes cash flows are distributed evenly throughout the year, producing a higher PV than end-of-year.",
      },
      {
        id: "dcf_25",
        question: "A DCF is most appropriate for companies with which characteristic?",
        options: ["No predictable cash flows", "Relatively predictable and stable free cash flows", "Exclusively asset-based value", "High near-term losses with no path to profitability"],
        correctIndex: 1,
        explanation: "DCF relies on discounting projected cash flows; it works best when FCF can be reasonably estimated over the forecast period.",
      },
      {
        id: "dcf_26",
        question: "What is the present value of $100 received in 2 years with a 10% discount rate (end-of-year)?",
        options: ["$82.6", "$90.9", "$100", "$110"],
        correctIndex: 0,
        explanation: "PV = 100 / (1.10)^2 = 100 / 1.21 ≈ $82.6.",
      },
      {
        id: "dcf_27",
        question: "When building a DCF, why do analysts often use EBITDA as a starting point rather than net income?",
        options: ["EBITDA is always higher than net income", "EBITDA is capital-structure and tax-neutral, making comparisons cleaner", "EBITDA excludes revenue", "Net income cannot be audited"],
        correctIndex: 1,
        explanation: "EBITDA removes the effects of financing (interest) and tax decisions, allowing analysts to evaluate core operating performance independently.",
      },
      {
        id: "dcf_28",
        question: "What effect does a large goodwill write-down have on a DCF valuation?",
        options: ["Directly reduces DCF value because it reduces cash flows", "Has no direct effect since goodwill impairment is non-cash", "Increases WACC", "Decreases terminal growth rate"],
        correctIndex: 1,
        explanation: "Goodwill impairment is a non-cash accounting charge. It reduces reported net income but is added back in the cash flow build, so it does not affect intrinsic DCF value.",
      },
      {
        id: "dcf_29",
        question: "Which formula correctly expresses WACC?",
        options: [
          "WACC = (E/V) × Ke + (D/V) × Kd",
          "WACC = (E/V) × Ke + (D/V) × Kd × (1 − T)",
          "WACC = Ke + Kd / 2",
          "WACC = Ke × Beta + Kd",
        ],
        correctIndex: 1,
        explanation: "WACC weights the after-tax cost of debt and cost of equity by their respective shares of total capital: (E/V)×Ke + (D/V)×Kd×(1−T).",
      },
      {
        id: "dcf_30",
        question: "A company's equity value per share from a DCF exceeds its current stock price. This implies the stock is:",
        options: ["Overvalued", "Undervalued", "Fairly valued", "Distressed"],
        correctIndex: 1,
        explanation: "If intrinsic value > market price, the stock is trading below its fundamental value — it is undervalued according to the DCF.",
      },
      {
        id: "dcf_31",
        question: "What is 'NOPAT' and how is it used in a DCF?",
        options: [
          "Net Operating Profit After Tax — used as the starting point for FCFF",
          "Non-Operating Profit And Tax — used in WACC calculation",
          "Net Outstanding Principal And Tax — used in debt schedules",
          "Normal Operating Profit After Trading — irrelevant to DCF",
        ],
        correctIndex: 0,
        explanation: "NOPAT = EBIT × (1 − Tax Rate). It represents after-tax operating earnings and is the starting point when computing FCFF from an operating perspective.",
      },
      {
        id: "dcf_32",
        question: "In a DCF, what does a negative FCFF in the early projection years indicate?",
        options: [
          "The company is bankrupt",
          "The company is investing heavily for growth, consuming more cash than it generates",
          "The WACC is too high",
          "Terminal value should be set to zero",
        ],
        correctIndex: 1,
        explanation: "Negative near-term FCFF is common for high-growth companies with large CapEx or working capital needs. Value is still captured in later years and terminal value.",
      },
      {
        id: "dcf_33",
        question: "Which of the following changes would increase the implied share price from a DCF?",
        options: ["Increase in WACC", "Decrease in terminal growth rate", "Increase in projected free cash flows", "Increase in net debt"],
        correctIndex: 2,
        explanation: "Higher projected FCFs increase the PV of cash flows in the numerator, directly raising Enterprise Value and therefore equity value per share.",
      },
      {
        id: "dcf_34",
        question: "What is the impact of stock-based compensation (SBC) on free cash flow in a DCF?",
        options: [
          "SBC is always ignored",
          "SBC is a non-cash add-back, but many analysts deduct it as a real cost to shareholders",
          "SBC reduces revenue",
          "SBC increases WACC",
        ],
        correctIndex: 1,
        explanation: "SBC is non-cash (added back in operating cash flow), but sophisticated analysts deduct it as a real economic cost because it dilutes shareholders.",
      },
      {
        id: "dcf_35",
        question: "Why is the terminal growth rate in a DCF capped below the WACC?",
        options: [
          "Regulatory requirement",
          "If g ≥ WACC, the Gordon Growth formula produces a negative or undefined Terminal Value",
          "Tax law restrictions",
          "It is not capped — g can exceed WACC",
        ],
        correctIndex: 1,
        explanation: "The denominator in the Gordon Growth model is (WACC − g). If g equals or exceeds WACC, the result is undefined or negative, which is economically nonsensical.",
      },
      {
        id: "dcf_36",
        question: "When performing a DCF on a cyclical company, analysts commonly:",
        options: [
          "Use a single-year snapshot as the base",
          "Use a mid-cycle normalized earnings figure to avoid over- or under-valuing at a peak/trough",
          "Ignore terminal value",
          "Set WACC to zero",
        ],
        correctIndex: 1,
        explanation: "Cyclical companies' earnings swing widely; using mid-cycle (normalized) figures prevents the valuation from being distorted by a temporary peak or trough.",
      },
      {
        id: "dcf_37",
        question: "What does 'tax-effecting' interest expense mean in the context of WACC?",
        options: [
          "Grossing up interest for tax purposes",
          "Multiplying the pre-tax cost of debt by (1 − tax rate) to reflect the interest tax shield",
          "Ignoring taxes entirely",
          "Adding taxes to the cost of equity",
        ],
        correctIndex: 1,
        explanation: "Because interest is tax-deductible, the actual after-tax cost of debt is Kd × (1 − T). This is what 'tax-effecting' refers to.",
      },
      {
        id: "dcf_38",
        question: "In a leveraged recapitalization, a company takes on new debt. What is the immediate effect on WACC?",
        options: [
          "WACC always increases",
          "WACC typically decreases (up to the optimal capital structure) due to cheaper after-tax debt",
          "WACC is unaffected",
          "WACC becomes equal to cost of equity",
        ],
        correctIndex: 1,
        explanation: "Debt is generally cheaper than equity (especially after-tax), so adding leverage typically lowers WACC up to a point before financial distress risk pushes it back up.",
      },
      {
        id: "dcf_39",
        question: "Which metric is most commonly used as the denominator in the EV/EBITDA exit multiple for terminal value?",
        options: ["Year 1 EBITDA", "Final projected year EBITDA", "Average EBITDA across all years", "LTM EBITDA at deal close"],
        correctIndex: 1,
        explanation: "The exit multiple is applied to the final projected year's EBITDA to estimate what a buyer would pay at the end of the forecast period.",
      },
      {
        id: "dcf_40",
        question: "What adjustment is made to move from Enterprise Value to equity market capitalization?",
        options: [
          "Add cash, subtract total debt, subtract preferred stock",
          "Subtract cash, add total debt, add preferred stock",
          "Subtract net debt and subtract minority interest",
          "Add back goodwill and intangibles",
        ],
        correctIndex: 2,
        explanation: "Equity Value = EV − Net Debt − Preferred Stock − Minority Interest. Net debt = Debt − Cash. Minority interest is a non-equity claim on assets.",
      },
      {
        id: "dcf_41",
        question: "What does a DCF 'football field' chart display?",
        options: [
          "A single point estimate of value",
          "A range of valuation outputs from multiple methodologies side by side",
          "A sensitivity on revenue growth only",
          "A waterfall of cash flows",
        ],
        correctIndex: 1,
        explanation: "A football field chart shows value ranges from multiple methods (DCF, comps, precedent transactions) as horizontal bars, giving a comprehensive valuation picture.",
      },
      {
        id: "dcf_42",
        question: "Reinvestment rate in a DCF context refers to:",
        options: [
          "The rate at which dividends are reinvested",
          "The proportion of NOPAT reinvested back into the business for growth",
          "The WACC applied to terminal value",
          "The beta of reinvested capital",
        ],
        correctIndex: 1,
        explanation: "Reinvestment rate = (CapEx − D&A + ΔNWC) / NOPAT. It measures how much of after-tax operating profit is plowed back for growth.",
      },
      {
        id: "dcf_43",
        question: "What is the implied perpetuity growth rate if Terminal Value was derived using an exit multiple?",
        options: [
          "It equals the risk-free rate",
          "It can be back-solved by rearranging the Gordon Growth formula to solve for g",
          "It is always zero",
          "It equals the cost of equity",
        ],
        correctIndex: 1,
        explanation: "Given the exit multiple terminal value, you can solve: g = WACC − (FCF_n+1 / TV). This provides a useful sanity check on the implied growth assumption.",
      },
      {
        id: "dcf_44",
        question: "How does share dilution from employee stock options affect DCF equity value per share?",
        options: [
          "It increases the per-share value",
          "It reduces per-share value by increasing the share count (treasury stock method)",
          "It has no effect",
          "It only matters for LBO analysis",
        ],
        correctIndex: 1,
        explanation: "In-the-money options are treated under the treasury stock method, adding net new shares to the denominator and reducing intrinsic value per share.",
      },
      {
        id: "dcf_45",
        question: "Increases in accounts receivable (AR) should be treated how in a DCF cash flow build?",
        options: [
          "Added as a source of cash",
          "Subtracted as a use of cash (increase in NWC)",
          "Ignored because AR is non-cash",
          "Added to EBITDA",
        ],
        correctIndex: 1,
        explanation: "An increase in AR means the company has recognized revenue but not yet collected cash — it is a use of cash and reduces free cash flow.",
      },
      {
        id: "dcf_46",
        question: "What does ROIC stand for and why is it relevant to DCF terminal value?",
        options: [
          "Return on Invested Capital — a high ROIC relative to WACC means growth creates value and justifies a higher terminal value",
          "Rate of Interest Capital — used to set the discount rate",
          "Ratio of Incremental Costs — used to project margins",
          "Return on Individual Contracts — irrelevant",
        ],
        correctIndex: 0,
        explanation: "ROIC measures how efficiently capital is deployed. If ROIC > WACC, growth adds value. This relationship underpins sustainable terminal value assumptions.",
      },
      {
        id: "dcf_47",
        question: "A DCF shows a company's implied EV/EBITDA of 4x vs. peers at 8x. What does this likely indicate?",
        options: [
          "The DCF is definitely correct and peers are overvalued",
          "The DCF assumptions may be too conservative, or there is a structural difference warranting further review",
          "The company should be liquidated",
          "The WACC should be doubled",
        ],
        correctIndex: 1,
        explanation: "A large divergence from peer multiples signals the DCF assumptions (growth, margins, WACC) may differ meaningfully from market expectations, warranting scrutiny.",
      },
      {
        id: "dcf_48",
        question: "Which of the following would cause a DCF to overvalue a company?",
        options: [
          "Using a too-high WACC",
          "Using a too-low terminal growth rate",
          "Using overly optimistic revenue projections",
          "Using end-of-year rather than mid-year discounting",
        ],
        correctIndex: 2,
        explanation: "Overly optimistic revenue projections lead to inflated FCF projections, overstating Enterprise Value.",
      },
      {
        id: "dcf_49",
        question: "In a two-stage DCF, Stage 1 is the explicit forecast period and Stage 2 is:",
        options: ["A second forecast at lower growth", "The terminal value representing value beyond the explicit forecast", "An alternative WACC scenario", "A separate segment valuation"],
        correctIndex: 1,
        explanation: "Stage 2 captures all value beyond the explicit forecast horizon via the terminal value formula, assuming stable long-run growth.",
      },
      {
        id: "dcf_50",
        question: "If a company's WACC is 10% and its ROIC is 8%, what does new investment do to firm value?",
        options: [
          "Creates value because ROIC is positive",
          "Destroys value because ROIC < WACC",
          "Is value-neutral",
          "Doubles the terminal value",
        ],
        correctIndex: 1,
        explanation: "When ROIC < WACC, each dollar reinvested generates less than its cost of capital — growth destroys value and the company would be worth more distributing cash.",
      },
    ],
  },
  {
    id: "lbo",
    title: "Leveraged Buyouts (LBO)",
    description: "Understand how private equity firms use debt to acquire companies and generate high returns through deleveraging.",
    difficulty: "Advanced",
    questions: [
      {
        id: "lbo_1",
        question: "What is the primary driver of equity returns in a Leveraged Buyout besides operational improvement?",
        options: ["Dividend payouts", "Debt paydown (deleveraging)", "Increasing WACC", "Reducing equity contribution"],
        correctIndex: 1,
        explanation: "As the company's cash flows pay down debt, equity value grows even if the exit multiple stays flat — this is the core mechanic of LBO returns.",
      },
      {
        id: "lbo_2",
        question: "What does IRR measure in the context of an LBO?",
        options: ["The interest rate on debt", "The annualized rate of return on the equity investment", "The WACC of the acquired company", "The terminal growth rate"],
        correctIndex: 1,
        explanation: "IRR (Internal Rate of Return) in an LBO measures the annualized return earned on the equity invested from entry to exit.",
      },
      {
        id: "lbo_3",
        question: "What is a 'sponsor' in an LBO transaction?",
        options: ["The company being acquired", "The private equity firm making the acquisition", "The bank providing the debt", "The management team"],
        correctIndex: 1,
        explanation: "The 'sponsor' is the private equity firm (financial buyer) that leads the LBO, contributes equity, and manages the investment.",
      },
      {
        id: "lbo_4",
        question: "Which type of company makes the ideal LBO candidate?",
        options: ["High-growth startup with no free cash flow", "Stable, cash-generative business with predictable earnings", "Company in financial distress", "Asset-light technology firm with volatile revenue"],
        correctIndex: 1,
        explanation: "Strong, predictable free cash flow is needed to service and repay debt. Stable businesses with high margins and low CapEx are ideal LBO targets.",
      },
      {
        id: "lbo_5",
        question: "In an LBO, what does 'leverage' refer to?",
        options: ["The company's operating margin", "Using borrowed money to amplify equity returns", "The sponsor's negotiating power", "The exit multiple"],
        correctIndex: 1,
        explanation: "Leverage means using significant debt financing in the acquisition. The debt amplifies equity returns (and losses) by controlling a larger asset with less equity.",
      },
      {
        id: "lbo_6",
        question: "What is the typical holding period for a PE firm in an LBO investment?",
        options: ["Less than 1 year", "3–7 years", "10–15 years", "20+ years"],
        correctIndex: 1,
        explanation: "PE funds typically target a 3–7 year hold period, during which they improve operations, pay down debt, and then exit at a profit.",
      },
      {
        id: "lbo_7",
        question: "If an LBO entry price is 8x EBITDA and exit price is 10x EBITDA with the same EBITDA, what drove additional value?",
        options: ["Debt paydown only", "Multiple expansion — the market now values the business higher", "Cost cutting reducing EBITDA", "Share dilution"],
        correctIndex: 1,
        explanation: "Multiple expansion occurs when the exit multiple exceeds the entry multiple. Even with flat EBITDA, the higher multiple applied at exit creates equity value.",
      },
      {
        id: "lbo_8",
        question: "What is a 'dividend recapitalization' in an LBO?",
        options: ["Converting debt to equity", "Taking on new debt post-acquisition to pay a special dividend to the sponsor", "Paying dividends from operating cash flows", "Refinancing existing equity"],
        correctIndex: 1,
        explanation: "A dividend recapitalization allows the PE firm to extract cash return during the hold period by having the portfolio company borrow more and pay a special dividend.",
      },
      {
        id: "lbo_9",
        question: "The minimum IRR threshold most PE funds target is approximately:",
        options: ["5–8%", "10–15%", "20–25%", "40–50%"],
        correctIndex: 2,
        explanation: "Most PE funds target a minimum IRR of 20–25% to justify the risk and illiquidity premium over public market alternatives.",
      },
      {
        id: "lbo_10",
        question: "What is a 'management rollover' in an LBO?",
        options: ["Replacing the management team entirely", "Existing management reinvesting a portion of their proceeds into equity of the new entity", "Rolling debt maturities forward", "A type of earn-out provision"],
        correctIndex: 1,
        explanation: "Management rollover aligns incentives: management swaps some sale proceeds for equity in the new LBO entity, sharing upside if the investment succeeds.",
      },
      {
        id: "lbo_11",
        question: "Which metric is most commonly used to assess a company's debt capacity in an LBO?",
        options: ["Revenue", "Net Income", "EBITDA (and related leverage multiples)", "Book equity"],
        correctIndex: 2,
        explanation: "Lenders assess debt capacity as a multiple of EBITDA (e.g., 5–6x). EBITDA approximates cash available to service debt.",
      },
      {
        id: "lbo_12",
        question: "What is 'PIK' interest in LBO financing?",
        options: ["Pay-In-Kind — interest accrues as additional debt rather than being paid in cash", "Principal Interest Kicker — a bonus paid to lenders at exit", "Predetermined Interest Key — a fixed rate mechanism", "Periodic Interim Payment"],
        correctIndex: 0,
        explanation: "PIK (Pay-In-Kind) interest compounds as additional principal rather than being paid in cash, preserving liquidity but increasing the debt burden over time.",
      },
      {
        id: "lbo_13",
        question: "In LBO financing, senior secured debt is typically priced at:",
        options: ["The highest interest rate due to first-lien status", "The lowest interest rate because lenders have the strongest claim on assets", "The same rate as mezzanine debt", "A fixed 5% regardless of credit quality"],
        correctIndex: 1,
        explanation: "Senior secured lenders have first priority in bankruptcy and therefore accept a lower interest rate. Risk and rate increase as you move down the capital structure.",
      },
      {
        id: "lbo_14",
        question: "What is the 'equity contribution' in an LBO?",
        options: ["The total enterprise value", "The cash the PE sponsor invests as equity (purchase price minus debt raised)", "The debt raised by the lenders", "Management's salary during the hold period"],
        correctIndex: 1,
        explanation: "Equity contribution = Purchase Price − Total Debt Raised. This is the PE firm's out-of-pocket cost and the denominator of the IRR calculation.",
      },
      {
        id: "lbo_15",
        question: "What is a 'portco' in PE terminology?",
        options: ["A type of debt instrument", "Portfolio company — a company owned by the PE fund", "The general partner of the fund", "A senior secured lender"],
        correctIndex: 1,
        explanation: "Portco is shorthand for 'portfolio company,' referring to any company owned and operated within a PE fund's investment portfolio.",
      },
      {
        id: "lbo_16",
        question: "An LBO model primarily answers what question for the sponsor?",
        options: ["What is the company's intrinsic fair value?", "At what price and leverage can we achieve our return hurdle?", "What is the company's WACC?", "How should the company be capitalized for an IPO?"],
        correctIndex: 1,
        explanation: "The LBO model determines the maximum price and optimal capital structure that allow the sponsor to meet its minimum return target (e.g., 20%+ IRR).",
      },
      {
        id: "lbo_17",
        question: "What is the effect of paying down debt faster (more cash sweep) on equity IRR in an LBO?",
        options: ["Decreases IRR by reducing cash available", "Increases IRR by growing equity value faster", "Has no effect on IRR", "Only affects MOIC, not IRR"],
        correctIndex: 1,
        explanation: "Faster debt paydown reduces the debt balance, increasing equity value at exit (since EV − Debt = Equity). Higher equity at exit improves both IRR and MOIC.",
      },
      {
        id: "lbo_18",
        question: "What does MOIC stand for and what does a 2.5x MOIC mean?",
        options: [
          "Multiple of Invested Capital — the sponsor returned 2.5x the equity invested",
          "Margin on Initial Costs — a profitability ratio",
          "Market Offer Investment Calculation — used in M&A",
          "Multiple of Interest Cost — a debt metric",
        ],
        correctIndex: 0,
        explanation: "MOIC = Total Proceeds / Equity Invested. A 2.5x MOIC means the sponsor received $2.50 for every $1.00 invested in equity, before considering the time value of money.",
      },
      {
        id: "lbo_19",
        question: "What is 'mezzanine debt' in an LBO capital structure?",
        options: ["First-lien senior secured debt", "Subordinated debt that sits between senior debt and equity, typically carrying higher rates or warrants", "A type of preferred equity", "Revolving credit facility"],
        correctIndex: 1,
        explanation: "Mezzanine debt is junior to senior secured debt but senior to equity. It compensates lenders for subordination risk through higher interest rates, PIK features, or warrants.",
      },
      {
        id: "lbo_20",
        question: "What is a 'term loan B' (TLB) and why is it common in LBOs?",
        options: [
          "A government-backed loan to small businesses",
          "An institutional leveraged loan with minimal amortization, traded in the secondary market",
          "A revolving credit facility for working capital",
          "A bond issued to retail investors",
        ],
        correctIndex: 1,
        explanation: "TLBs have minimal amortization (~1%/year) and bullet maturities, preserving cash flow for operations. They are widely used in LBOs and traded among institutional investors.",
      },
      {
        id: "lbo_21",
        question: "How does a higher purchase price multiple (entry multiple) affect LBO returns, all else equal?",
        options: ["Increases IRR by showing confidence", "Decreases IRR because more equity is required and/or exit multiple expansion is harder", "Has no effect on IRR", "Increases MOIC but decreases IRR"],
        correctIndex: 1,
        explanation: "A higher entry multiple increases the purchase price, requiring more equity and/or debt. With the same exit value, higher equity invested means lower returns.",
      },
      {
        id: "lbo_22",
        question: "What is a 'covenant-lite' loan?",
        options: ["A loan with extremely high covenants protecting lenders", "A leveraged loan with few or no maintenance covenants, giving borrowers more flexibility", "A government-guaranteed loan", "A loan with zero interest"],
        correctIndex: 1,
        explanation: "Covenant-lite (cov-lite) loans omit maintenance financial covenants, reducing lender protections. They became prevalent in PE deals during favorable credit markets.",
      },
      {
        id: "lbo_23",
        question: "What is an 'add-on acquisition' in the context of a PE platform strategy?",
        options: [
          "Additional equity contributed by the sponsor mid-hold",
          "Acquiring smaller companies to bolt on to the existing platform company",
          "Adding debt tranches post-close",
          "A secondary buyout of the platform company",
        ],
        correctIndex: 1,
        explanation: "A buy-and-build strategy uses the platform company to acquire smaller 'add-ons,' growing scale, synergies, and potentially driving multiple expansion at exit.",
      },
      {
        id: "lbo_24",
        question: "In an LBO, what is a 'cash sweep'?",
        options: ["A fee paid to lenders", "Using excess free cash flow to voluntarily pay down debt principal ahead of schedule", "Sweeping cash to offshore accounts", "A working capital adjustment at close"],
        correctIndex: 1,
        explanation: "A cash sweep (or excess cash flow sweep) provision requires the company to use a portion of free cash flow to prepay debt, accelerating deleveraging.",
      },
      {
        id: "lbo_25",
        question: "What is the difference between a 'financial buyer' and a 'strategic buyer'?",
        options: [
          "Financial buyers pay with stock; strategic buyers pay with cash",
          "Financial buyers (PE firms) seek financial returns; strategic buyers (corporates) seek synergies and strategic fit",
          "Financial buyers are always higher bidders",
          "Strategic buyers use more leverage",
        ],
        correctIndex: 1,
        explanation: "Strategic buyers can pay synergy premiums and often outbid PE firms. PE firms rely on financial engineering and operational improvement to generate returns.",
      },
      {
        id: "lbo_26",
        question: "A higher EBITDA margin in an LBO target generally leads to:",
        options: ["Less free cash flow", "More free cash flow, supporting higher debt capacity and better returns", "Lower valuation", "Higher WACC"],
        correctIndex: 1,
        explanation: "Higher margins mean more of each revenue dollar falls to EBITDA, generating more cash to service debt and driving equity value growth.",
      },
      {
        id: "lbo_27",
        question: "What is a 'secondary buyout' (SBO)?",
        options: [
          "An IPO of a portfolio company",
          "A PE firm selling a portfolio company to another PE firm",
          "A company conducting a second leveraged recapitalization",
          "A management buyout after a failed primary LBO",
        ],
        correctIndex: 1,
        explanation: "An SBO occurs when one PE fund sells a portco to another PE fund. Common in mature PE markets, though it can raise concerns about value-creation runway.",
      },
      {
        id: "lbo_28",
        question: "What is 'purchase price allocation' (PPA) in an LBO?",
        options: [
          "Allocating the acquisition price among assets, liabilities, and goodwill for accounting purposes",
          "Deciding how much equity vs. debt to use",
          "Allocating management bonuses",
          "Setting the exit price",
        ],
        correctIndex: 0,
        explanation: "Under acquisition accounting, PPA requires identifying and fair-valuing all acquired assets and liabilities. Residual value is recorded as goodwill.",
      },
      {
        id: "lbo_29",
        question: "In an LBO model, 'sources and uses' refers to:",
        options: [
          "Revenue sources and expense categories",
          "Where the money to buy the company comes from (sources) and how it is spent (uses)",
          "Debt repayment schedule",
          "Cash flow statement categories",
        ],
        correctIndex: 1,
        explanation: "Sources (equity, debt, rollover equity) must equal Uses (purchase price, fees, refinanced debt). Balancing sources and uses is step one of any LBO model.",
      },
      {
        id: "lbo_30",
        question: "What is a 'general partner' (GP) in a PE fund context?",
        options: [
          "A limited liability investor in the fund",
          "The PE firm that manages the fund and makes investment decisions",
          "A senior secured lender",
          "An independent advisor to the fund",
        ],
        correctIndex: 1,
        explanation: "The GP (PE firm) manages fund operations, makes investment decisions, and typically earns a 2% management fee and 20% carried interest on profits.",
      },
      {
        id: "lbo_31",
        question: "What is 'carried interest' and how is it calculated?",
        options: [
          "Interest accrued on PE fund debt",
          "The GP's share of profits (typically 20%) above a hurdle rate",
          "Management fees charged annually",
          "A tax on fund distributions",
        ],
        correctIndex: 1,
        explanation: "Carried interest (carry) is the performance fee — usually 20% of profits above the hurdle rate (commonly 8%). It aligns GP incentives with LP returns.",
      },
      {
        id: "lbo_32",
        question: "What is a 'limited partner' (LP) in a PE fund?",
        options: [
          "The PE firm managing the fund",
          "Passive investors who commit capital but have no management role",
          "Senior debt lenders",
          "A government regulator",
        ],
        correctIndex: 1,
        explanation: "LPs (pension funds, endowments, family offices, etc.) provide the majority of capital. They have limited liability and receive returns net of GP fees and carry.",
      },
      {
        id: "lbo_33",
        question: "What is 'EBITDA add-backs' and why do they matter in an LBO?",
        options: [
          "Add-backs reduce EBITDA to be more conservative",
          "Add-backs are adjustments to reported EBITDA for one-time or non-recurring items, increasing adjusted EBITDA and thus debt capacity",
          "Add-backs refer to tax adjustments only",
          "Add-backs have no impact on deal pricing",
        ],
        correctIndex: 1,
        explanation: "Buyers and sellers negotiate add-backs to EBITDA (e.g., restructuring charges, management fees). Higher adjusted EBITDA supports a higher purchase price and more debt.",
      },
      {
        id: "lbo_34",
        question: "What is the 'hurdle rate' in a PE fund?",
        options: [
          "The minimum IRR the GP must deliver before earning carried interest",
          "The maximum interest rate on LBO debt",
          "The minimum EBITDA multiple for an acquisition",
          "The fund's target leverage ratio",
        ],
        correctIndex: 0,
        explanation: "The hurdle rate (preferred return, commonly 8%) is the minimum annualized return LPs must receive before the GP begins collecting carried interest.",
      },
      {
        id: "lbo_35",
        question: "What is a 'PIK toggle' note?",
        options: [
          "A note that converts between equity and debt",
          "A debt instrument allowing the issuer to switch between cash and PIK interest payments",
          "A fixed-rate bond with no PIK feature",
          "A note that resets interest rates periodically",
        ],
        correctIndex: 1,
        explanation: "PIK toggle notes give the borrower flexibility to pay cash interest when liquidity is good or toggle to PIK (accrue) when cash is tight, preserving operational flexibility.",
      },
      {
        id: "lbo_36",
        question: "What is 'DSCR' and why is it used in LBO lending decisions?",
        options: [
          "Debt Service Coverage Ratio — measures whether operating cash flow covers interest and principal payments",
          "Discounted Share Capital Ratio — used in equity valuation",
          "Default Sensitivity Credit Rating — used by rating agencies",
          "Distribution to Shareholders Conversion Ratio",
        ],
        correctIndex: 0,
        explanation: "DSCR = Operating Cash Flow / Debt Service. Lenders require a minimum DSCR (e.g., 1.2x) to ensure the company can service its debt obligations comfortably.",
      },
      {
        id: "lbo_37",
        question: "Which of the following is NOT a typical exit route for a PE investment?",
        options: ["IPO", "Strategic sale", "Secondary buyout", "Debt restructuring into equity"],
        correctIndex: 3,
        explanation: "Common PE exits include IPO, strategic sale, and secondary buyout. Debt restructuring into equity is a distressed situation, not a planned PE exit strategy.",
      },
      {
        id: "lbo_38",
        question: "A longer hold period in an LBO, all else equal, generally does what to IRR?",
        options: ["Increases IRR because MOIC grows", "Decreases IRR because the same return is spread over more years", "Has no effect on IRR", "Doubles the MOIC"],
        correctIndex: 1,
        explanation: "IRR is time-sensitive. Achieving the same MOIC over 7 years vs. 4 years results in a materially lower annualized IRR.",
      },
      {
        id: "lbo_39",
        question: "What role does a revolver play in an LBO capital structure?",
        options: [
          "It is the primary acquisition financing",
          "It provides flexible working capital liquidity, drawn and repaid as needed",
          "It pays the management fee to the GP",
          "It converts to equity at exit",
        ],
        correctIndex: 1,
        explanation: "A revolving credit facility (revolver) is a flexible liquidity buffer for working capital needs. It is typically undrawn at close and used/repaid during operations.",
      },
      {
        id: "lbo_40",
        question: "What does 'leveraged beta' capture that 'unlevered beta' does not?",
        options: [
          "Business / operating risk",
          "Both business risk and additional financial risk from debt in the capital structure",
          "The tax shield from depreciation",
          "Revenue volatility only",
        ],
        correctIndex: 1,
        explanation: "Levered beta reflects both operating risk and the amplifying effect of debt (financial risk). As leverage increases, equity becomes more volatile, raising levered beta.",
      },
      {
        id: "lbo_41",
        question: "What is a 'staple financing' in an M&A/LBO context?",
        options: [
          "Financing committed by the target's existing lenders",
          "Debt financing pre-arranged by the seller's bank and offered to all potential bidders",
          "A management incentive plan",
          "A seller note provided by the target's shareholders",
        ],
        correctIndex: 1,
        explanation: "Staple financing is arranged by the sell-side adviser and offered as a ready-made debt package to bidders, facilitating faster deal closings.",
      },
      {
        id: "lbo_42",
        question: "What is 'deal fatigue' risk in an LBO transaction?",
        options: [
          "The risk that the target's EBITDA declines during the hold period",
          "The risk that prolonged negotiations or due diligence cause key personnel, customers, or lenders to withdraw",
          "A regulatory risk from antitrust review",
          "The risk of missing the GP's fund return target",
        ],
        correctIndex: 1,
        explanation: "Deal fatigue occurs when extended processes demoralize management, cause customer uncertainty, or exhaust financing commitments — all risks in complex LBO transactions.",
      },
      {
        id: "lbo_43",
        question: "In an LBO, what is 'net leverage'?",
        options: [
          "Total debt divided by EBITDA",
          "Total debt minus cash, divided by EBITDA",
          "Equity value divided by debt",
          "EBIT divided by interest expense",
        ],
        correctIndex: 1,
        explanation: "Net leverage = (Total Debt − Cash) / EBITDA. Netting out cash reflects the true debt burden since cash can immediately repay debt.",
      },
      {
        id: "lbo_44",
        question: "What is the 'J-curve' in private equity fund performance?",
        options: [
          "The typical IRR trajectory of individual investments",
          "The early-year negative fund returns due to fees and unrealized investments, followed by positive returns as exits occur",
          "The relationship between MOIC and IRR",
          "A graphical representation of EBITDA growth",
        ],
        correctIndex: 1,
        explanation: "Early in a fund's life, fees are charged before exits occur, causing net returns to dip negative. Returns recover and turn positive as investments are exited — forming a J shape.",
      },
      {
        id: "lbo_45",
        question: "Which covenant type requires a company to maintain a financial ratio above/below a threshold on an ongoing basis?",
        options: ["Incurrence covenant", "Maintenance covenant", "Cross-default covenant", "Change-of-control covenant"],
        correctIndex: 1,
        explanation: "Maintenance covenants (common in bank loans) require the borrower to continuously satisfy financial ratios (e.g., leverage ratio). Breach triggers a covenant default.",
      },
      {
        id: "lbo_46",
        question: "What is 'transaction value' vs. 'equity value' in an LBO?",
        options: [
          "They are the same thing",
          "Transaction value is the total enterprise purchase price; equity value is what the PE firm pays for equity after deducting assumed debt",
          "Transaction value excludes fees; equity value includes fees",
          "Equity value is always higher than transaction value",
        ],
        correctIndex: 1,
        explanation: "Transaction value (enterprise value) includes debt assumed. Equity value = Transaction Value − Debt + Cash. The sponsor funds equity value from its own capital.",
      },
      {
        id: "lbo_47",
        question: "What is 'equity kicker' or 'equity sweetener' in mezzanine debt?",
        options: [
          "A cash bonus paid to equity holders",
          "Warrants or options given to mezzanine lenders allowing them to participate in equity upside",
          "A reduced interest rate on senior debt",
          "A PIK feature on high-yield bonds",
        ],
        correctIndex: 1,
        explanation: "Mezzanine lenders receive warrants (equity kickers) as compensation for subordination risk, allowing them to benefit from equity appreciation if the deal succeeds.",
      },
      {
        id: "lbo_48",
        question: "Why is free cash flow conversion critical in an LBO analysis?",
        options: [
          "It determines the entry purchase price",
          "It measures how efficiently EBITDA converts to actual cash available for debt repayment",
          "It sets the exit multiple",
          "It determines the hurdle rate",
        ],
        correctIndex: 1,
        explanation: "FCF conversion = FCF / EBITDA. High conversion means most EBITDA becomes real cash, which pays down debt faster and drives equity value growth.",
      },
      {
        id: "lbo_49",
        question: "What is a 'management buyout' (MBO)?",
        options: [
          "A PE firm buying out a company's management team",
          "The existing management team acquiring the company, typically with PE backing",
          "A buyout funded entirely by management's personal savings",
          "A buyout of a government-owned entity",
        ],
        correctIndex: 1,
        explanation: "In an MBO, management partners with a PE firm, contributing rollover equity and operational expertise while the PE firm provides capital and deal structuring.",
      },
      {
        id: "lbo_50",
        question: "What is the significance of the 'equity cushion' in an LBO?",
        options: [
          "It determines management compensation",
          "The equity below the debt in the capital structure; a larger cushion gives lenders more protection against loss",
          "The amount of PIK interest accrued",
          "The difference between entry and exit EBITDA",
        ],
        correctIndex: 1,
        explanation: "Equity cushion = Equity Value / Enterprise Value. A thicker cushion (more equity relative to total capital) means lenders face less default risk and can recover more in a downside scenario.",
      },
    ],
  },
  {
    id: "accounting",
    title: "Core Accounting",
    description: "The language of finance. Learn how the three financial statements interconnect and impact valuation.",
    difficulty: "Beginner",
    questions: [
      {
        id: "acc_1",
        question: "If Depreciation increases by $10, how does it affect Cash Flow, assuming a 20% tax rate?",
        options: ["Cash flow decreases by $10", "Cash flow increases by $2", "Cash flow increases by $8", "Cash flow remains unchanged"],
        correctIndex: 2,
        explanation: "Depreciation reduces Net Income by $10 × (1 − 20%) = $8 after-tax. In the cash flow statement, the $10 non-cash charge is added back, netting to a +$8 cash benefit.",
      },
      {
        id: "acc_2",
        question: "Which financial statement shows a company's assets, liabilities, and shareholders' equity at a point in time?",
        options: ["Income Statement", "Cash Flow Statement", "Balance Sheet", "Statement of Retained Earnings"],
        correctIndex: 2,
        explanation: "The Balance Sheet is a snapshot at a specific date, showing what the company owns (assets), owes (liabilities), and the residual claim of shareholders (equity).",
      },
      {
        id: "acc_3",
        question: "What is the accounting equation?",
        options: ["Revenue − Expenses = Net Income", "Assets = Liabilities + Shareholders' Equity", "Cash = Revenue − CapEx", "EBITDA = Net Income + D&A + Interest + Taxes"],
        correctIndex: 1,
        explanation: "The fundamental accounting equation — Assets = Liabilities + Shareholders' Equity — must always balance and underpins double-entry bookkeeping.",
      },
      {
        id: "acc_4",
        question: "Under accrual accounting, revenue is recognized when:",
        options: ["Cash is received", "The good/service is delivered and earned, regardless of cash receipt", "The invoice is issued", "The contract is signed"],
        correctIndex: 1,
        explanation: "Accrual accounting recognizes revenue when earned (performance obligation satisfied), not when cash is collected — creating timing differences that flow through working capital.",
      },
      {
        id: "acc_5",
        question: "What is EBITDA an approximation of?",
        options: ["Net income adjusted for taxes only", "Operating cash flow before working capital changes", "Gross profit minus SG&A", "Revenue minus COGS"],
        correctIndex: 1,
        explanation: "EBITDA (Earnings Before Interest, Taxes, Depreciation, Amortization) approximates operating cash flow before working capital movements and is a widely used proxy for cash generation.",
      },
      {
        id: "acc_6",
        question: "If accounts receivable increases, what does that imply?",
        options: ["The company collected more cash than it recognized in revenue", "The company recognized revenue but has not yet collected the cash", "The company's revenue decreased", "Inventory is being sold faster"],
        correctIndex: 1,
        explanation: "Rising AR means revenue was earned (recorded on the income statement) but cash hasn't been received yet — a use of cash and an increase in working capital.",
      },
      {
        id: "acc_7",
        question: "What does 'goodwill' represent on the balance sheet?",
        options: ["The market value of the company's brand", "The excess purchase price paid over the fair value of net identifiable assets in an acquisition", "Long-term investments in other companies", "The book value of intellectual property"],
        correctIndex: 1,
        explanation: "Goodwill = Acquisition Price − Fair Value of Net Identifiable Assets. It represents intangibles like synergies, brand reputation, and customer relationships.",
      },
      {
        id: "acc_8",
        question: "Which of the following is a non-cash charge that reduces Net Income but is added back in the Cash Flow Statement?",
        options: ["Interest expense", "Income tax expense", "Depreciation & Amortization", "Cost of Goods Sold"],
        correctIndex: 2,
        explanation: "D&A is a non-cash accounting charge. It reduces reported earnings but requires no cash outflow, so it's added back in the operating section of the cash flow statement.",
      },
      {
        id: "acc_9",
        question: "What is the difference between FIFO and LIFO inventory accounting?",
        options: [
          "FIFO sells newest inventory first; LIFO sells oldest first",
          "FIFO sells oldest inventory first; LIFO sells newest first",
          "FIFO and LIFO produce the same gross profit in all circumstances",
          "LIFO is required under IFRS",
        ],
        correctIndex: 1,
        explanation: "FIFO (First In, First Out) records oldest units as sold first; LIFO (Last In, First Out) records newest units as sold first. In rising price environments, LIFO produces higher COGS and lower profits.",
      },
      {
        id: "acc_10",
        question: "How does a $100 increase in inventory affect the three financial statements (no cash paid yet — on credit)?",
        options: [
          "No change to any statement",
          "Assets +$100, Liabilities +$100; no Income Statement or Cash Flow impact",
          "Revenue +$100, Net Income +$100, Assets +$100",
          "Cash −$100, Inventory +$100",
        ],
        correctIndex: 1,
        explanation: "Buying inventory on credit: Inventory (asset) +$100, Accounts Payable (liability) +$100. No income statement impact until sold; no cash flow impact until paid.",
      },
      {
        id: "acc_11",
        question: "What is deferred revenue and where does it appear on the balance sheet?",
        options: [
          "Revenue already collected and recognized; appears in equity",
          "Cash received for goods/services not yet delivered; a liability until earned",
          "Revenue expected from future contracts; an asset",
          "Uncollected receivables; an asset",
        ],
        correctIndex: 1,
        explanation: "Deferred revenue (unearned revenue) is a liability because the company has been paid but hasn't yet fulfilled its obligation. Revenue is recognized as delivery occurs.",
      },
      {
        id: "acc_12",
        question: "What is operating leverage?",
        options: [
          "The use of debt to amplify equity returns",
          "The sensitivity of operating income to changes in revenue, driven by fixed cost structure",
          "The ratio of debt to total assets",
          "A measure of interest coverage",
        ],
        correctIndex: 1,
        explanation: "High operating leverage means a high proportion of fixed costs. Revenue increases flow rapidly to profit because fixed costs don't scale with volume.",
      },
      {
        id: "acc_13",
        question: "When a company issues stock, what happens to the balance sheet?",
        options: [
          "Assets decrease, Equity decreases",
          "Cash (asset) increases and Shareholders' Equity increases by the same amount",
          "Liabilities increase, Assets decrease",
          "No change — stock issuance is off balance sheet",
        ],
        correctIndex: 1,
        explanation: "Issuing stock raises cash (asset increases) and increases equity (common stock + additional paid-in capital). The accounting equation remains balanced.",
      },
      {
        id: "acc_14",
        question: "What does the quick ratio measure?",
        options: [
          "How quickly inventory turns over",
          "Ability to meet short-term obligations using liquid assets (excl. inventory)",
          "Gross profit as a percentage of revenue",
          "Operating cash flow relative to current liabilities",
        ],
        correctIndex: 1,
        explanation: "Quick Ratio = (Cash + Short-Term Investments + Receivables) / Current Liabilities. It measures immediate liquidity more conservatively than the current ratio by excluding inventory.",
      },
      {
        id: "acc_15",
        question: "Net working capital is defined as:",
        options: ["Total assets minus total liabilities", "Current assets minus current liabilities", "Cash minus short-term debt", "Inventory plus receivables"],
        correctIndex: 1,
        explanation: "NWC = Current Assets − Current Liabilities. It represents the short-term operational liquidity of the business.",
      },
      {
        id: "acc_16",
        question: "What is the difference between accounts payable and accounts receivable?",
        options: [
          "AP: money owed to the company; AR: money the company owes",
          "AR: money owed to the company by customers; AP: money the company owes to suppliers",
          "They are the same thing",
          "AP is an asset; AR is a liability",
        ],
        correctIndex: 1,
        explanation: "AR is an asset (customers owe you money); AP is a liability (you owe suppliers money). Higher AP (paying suppliers later) is a source of cash; higher AR (collecting slower) is a use of cash.",
      },
      {
        id: "acc_17",
        question: "If a company buys back $50 of its own stock, what happens on the balance sheet?",
        options: [
          "Cash +$50, Treasury Stock +$50",
          "Cash −$50, Treasury Stock +$50 (contra-equity), Net Equity −$50",
          "Assets +$50, Liabilities +$50",
          "No balance sheet impact",
        ],
        correctIndex: 1,
        explanation: "Share repurchases reduce cash and increase treasury stock (a contra-equity account), reducing total shareholders' equity by the repurchase price.",
      },
      {
        id: "acc_18",
        question: "What is the matching principle in accounting?",
        options: [
          "Assets must always equal liabilities",
          "Expenses should be recognized in the same period as the revenues they help generate",
          "Revenue is matched to cash inflows",
          "Depreciation matches asset life to book value",
        ],
        correctIndex: 1,
        explanation: "The matching principle pairs expenses with the revenues they generate in the same reporting period, regardless of when cash is paid.",
      },
      {
        id: "acc_19",
        question: "What is the difference between gross profit and operating income?",
        options: [
          "They are identical",
          "Gross profit = Revenue − COGS; Operating Income = Gross Profit − Operating Expenses (SG&A, R&D)",
          "Operating income includes interest expense; gross profit does not",
          "Gross profit is after-tax; operating income is pre-tax",
        ],
        correctIndex: 1,
        explanation: "Gross profit strips out only COGS. Operating income (EBIT) further deducts operating expenses like SG&A, R&D, and D&A.",
      },
      {
        id: "acc_20",
        question: "What does the days sales outstanding (DSO) metric tell you?",
        options: [
          "How many days of inventory a company holds",
          "The average number of days it takes to collect payment after a sale",
          "How long it takes to pay suppliers",
          "The number of days revenue covers operating costs",
        ],
        correctIndex: 1,
        explanation: "DSO = (Accounts Receivable / Revenue) × 365. A rising DSO may signal customers are paying slower, which is a liquidity concern.",
      },
      {
        id: "acc_21",
        question: "Under what accounting method is revenue recognized only when cash is received?",
        options: ["Accrual accounting", "Cash basis accounting", "Mark-to-market accounting", "Modified accrual accounting"],
        correctIndex: 1,
        explanation: "Cash basis accounting recognizes revenue and expenses only when cash changes hands, unlike accrual which records them when earned/incurred.",
      },
      {
        id: "acc_22",
        question: "What does it mean for a company to be 'asset-light'?",
        options: [
          "The company has low net income",
          "The company generates revenue with relatively few fixed assets, relying on intellectual capital, platforms, or outsourcing",
          "The company holds only current assets",
          "The company has no goodwill",
        ],
        correctIndex: 1,
        explanation: "Asset-light businesses (e.g., software companies) require minimal physical assets to grow, resulting in high returns on assets and capital-efficient scaling.",
      },
      {
        id: "acc_23",
        question: "When a company capitalizes rather than expenses a cost, what is the immediate effect?",
        options: [
          "Net Income is lower in the current period",
          "Net Income is higher in the current period (cost spread over asset life rather than expensed immediately)",
          "Cash flow is higher in the current period",
          "The balance sheet is unaffected",
        ],
        correctIndex: 1,
        explanation: "Capitalizing a cost creates an asset and depreciates/amortizes it over time rather than recognizing the full expense immediately, boosting near-term net income.",
      },
      {
        id: "acc_24",
        question: "What is the interest coverage ratio and what does it measure?",
        options: [
          "Debt / EBITDA — measures total leverage",
          "EBIT / Interest Expense — measures how many times earnings can cover interest obligations",
          "Cash / Total Debt — measures liquidity",
          "Net Income / Revenue — measures profitability",
        ],
        correctIndex: 1,
        explanation: "Interest Coverage = EBIT / Interest Expense. A ratio below 1.0x means the company cannot cover interest from operations — a serious distress signal.",
      },
      {
        id: "acc_25",
        question: "What causes a 'timing difference' between net income and cash flow from operations?",
        options: [
          "Differences in revenue recognition and actual cash collection (e.g., AR, AP, deferred revenue)",
          "Tax rate changes",
          "Changes in the capital structure",
          "Goodwill amortization",
        ],
        correctIndex: 0,
        explanation: "Accrual accounting creates differences between recognized revenue/expense and actual cash flows — captured in working capital changes on the cash flow statement.",
      },
      {
        id: "acc_26",
        question: "How does paying down debt affect the three financial statements?",
        options: [
          "Income Statement: interest expense falls; Balance Sheet: cash falls, debt falls; CFS: financing outflow",
          "Income Statement: revenue falls; Balance Sheet: equity falls",
          "No impact on any statement",
          "Balance Sheet: assets increase",
        ],
        correctIndex: 0,
        explanation: "Debt repayment reduces cash (asset) and debt (liability) on the balance sheet, appears as a financing outflow on the CFS, and reduces future interest expense on the income statement.",
      },
      {
        id: "acc_27",
        question: "What is the purpose of the statement of cash flows?",
        options: [
          "To show profitability over a period",
          "To reconcile net income to actual cash generated/used, categorized by operating, investing, and financing activities",
          "To show the book value of assets",
          "To report equity transactions only",
        ],
        correctIndex: 1,
        explanation: "The cash flow statement bridges net income (accrual) and actual cash. It shows whether a profitable company is generating or consuming cash across three activity categories.",
      },
      {
        id: "acc_28",
        question: "What is the difference between operating and capital leases (under older US GAAP pre-ASC 842)?",
        options: [
          "Operating leases appeared on balance sheet; capital leases did not",
          "Capital leases were treated like asset ownership (on balance sheet); operating leases were off-balance-sheet expenses",
          "They are identical under US GAAP",
          "Capital leases only applied to real estate",
        ],
        correctIndex: 1,
        explanation: "Under old GAAP, capital leases were recognized as assets/liabilities on the balance sheet; operating leases were expensed as rent. ASC 842 brought most leases onto the balance sheet.",
      },
      {
        id: "acc_29",
        question: "What does 'diluted EPS' account for that 'basic EPS' does not?",
        options: [
          "Tax adjustments",
          "Potential dilution from stock options, warrants, and convertible securities",
          "Minority interest deductions",
          "Foreign currency translation",
        ],
        correctIndex: 1,
        explanation: "Diluted EPS uses the treasury stock method to include all potentially dilutive securities, giving a more conservative (lower) per-share earnings figure.",
      },
      {
        id: "acc_30",
        question: "What is 'working capital management' and why does it matter?",
        options: [
          "Managing the long-term capital structure",
          "Optimizing current assets and liabilities to maximize liquidity and minimize the cash conversion cycle",
          "Setting the capital expenditure budget",
          "Deciding on dividend policy",
        ],
        correctIndex: 1,
        explanation: "Efficient working capital management (collecting AR faster, paying AP later, reducing inventory) frees up cash and reduces financing needs.",
      },
      {
        id: "acc_31",
        question: "What is an 'impairment charge'?",
        options: [
          "A charge for accelerated depreciation",
          "A write-down of an asset's book value when its carrying amount exceeds its recoverable amount",
          "A penalty for late tax filings",
          "An adjustment to intangible amortization",
        ],
        correctIndex: 1,
        explanation: "When an asset's fair value falls below its carrying (book) value, companies recognize an impairment charge — a non-cash expense that reduces net income and the asset's balance sheet value.",
      },
      {
        id: "acc_32",
        question: "Under IFRS, goodwill is:",
        options: [
          "Amortized over 40 years",
          "Not amortized but tested annually for impairment",
          "Always expensed immediately",
          "Amortized over 10 years",
        ],
        correctIndex: 1,
        explanation: "IFRS (and US GAAP post-SFAS 142) do not amortize goodwill. Instead, companies test it annually (or when indicators exist) for impairment.",
      },
      {
        id: "acc_33",
        question: "What is 'return on equity' (ROE) and what does it measure?",
        options: [
          "Net Income / Total Assets — measures asset efficiency",
          "Net Income / Shareholders' Equity — measures how efficiently equity is deployed to generate profit",
          "EBIT / Revenue — measures operating margin",
          "Dividends / Share Price — measures yield",
        ],
        correctIndex: 1,
        explanation: "ROE = Net Income / Shareholders' Equity. It measures the return generated for equity holders from the capital they've invested.",
      },
      {
        id: "acc_34",
        question: "What is the DuPont analysis breakdown of ROE?",
        options: [
          "ROE = Net Margin × Revenue",
          "ROE = Net Margin × Asset Turnover × Equity Multiplier",
          "ROE = EBITDA Margin × WACC",
          "ROE = Gross Margin × Operating Leverage",
        ],
        correctIndex: 1,
        explanation: "DuPont decomposes ROE into: (Net Income/Revenue) × (Revenue/Assets) × (Assets/Equity) — isolating profitability, efficiency, and leverage drivers.",
      },
      {
        id: "acc_35",
        question: "What happens to retained earnings when a company pays a cash dividend?",
        options: [
          "Retained earnings increase",
          "Retained earnings decrease by the dividend amount",
          "Retained earnings are unaffected",
          "Retained earnings are transferred to paid-in capital",
        ],
        correctIndex: 1,
        explanation: "Cash dividends reduce retained earnings (and cash). They are distributions of profits to shareholders, not expenses, so they don't affect the income statement.",
      },
      {
        id: "acc_36",
        question: "What does 'working capital' represent for a manufacturing company?",
        options: [
          "Long-term debt capacity",
          "Short-term operational assets (inventory, AR) minus short-term operational liabilities (AP, accruals)",
          "Capital expenditures for the year",
          "Shareholders' equity minus goodwill",
        ],
        correctIndex: 1,
        explanation: "Working capital captures the short-term cash cycle: buying inventory, producing goods, selling on credit (AR), and paying suppliers (AP). A growing business typically requires more working capital.",
      },
      {
        id: "acc_37",
        question: "What is the tax impact of depreciation on a company's cash taxes paid?",
        options: [
          "Depreciation increases taxes because it increases book income",
          "Depreciation reduces taxable income, lowering cash taxes paid",
          "Depreciation has no tax effect",
          "Depreciation only affects deferred taxes, not cash taxes",
        ],
        correctIndex: 1,
        explanation: "Depreciation is tax-deductible (though accelerated for tax purposes vs. straight-line for GAAP), reducing taxable income and thus cash taxes paid.",
      },
      {
        id: "acc_38",
        question: "What is a 'deferred tax liability'?",
        options: [
          "A tax refund owed to the company",
          "A future tax obligation arising because taxable income is temporarily lower than book income",
          "Prepaid taxes on the balance sheet",
          "A tax penalty for late payment",
        ],
        correctIndex: 1,
        explanation: "When companies use accelerated depreciation for tax (reducing current taxes) but straight-line for GAAP, they create a deferred tax liability — future taxes they'll eventually owe.",
      },
      {
        id: "acc_39",
        question: "In a merger, what is 'purchase accounting'?",
        options: [
          "Adjusting the target's book value to reflect historical cost",
          "Fair-valuing all acquired assets and liabilities, with residual excess recorded as goodwill",
          "Recording only tangible assets at market value",
          "Averaging the acquirer's and target's book values",
        ],
        correctIndex: 1,
        explanation: "Under purchase (acquisition) accounting, all identifiable assets and liabilities are marked to fair value. Any premium paid above fair net assets is goodwill.",
      },
      {
        id: "acc_40",
        question: "What is 'earnings quality' and what are red flags that indicate poor quality?",
        options: [
          "How high EPS is relative to peers",
          "The extent to which reported earnings reflect sustainable cash generation; red flags include rising AR relative to revenue and large non-recurring gains",
          "The auditor's opinion on financial statements",
          "The consistency of the gross margin year-over-year",
        ],
        correctIndex: 1,
        explanation: "High earnings quality means profits convert well to cash and are sustainable. Red flags: AR growing faster than revenue (aggressive recognition), frequent one-time charges, large discretionary accruals.",
      },
      {
        id: "acc_41",
        question: "What is the difference between EV (Enterprise Value) and Market Cap?",
        options: [
          "They are identical",
          "EV = Market Cap + Net Debt + Preferred Stock + Minority Interest; it represents total firm value irrespective of capital structure",
          "EV excludes cash; Market Cap includes it",
          "Market Cap includes debt; EV does not",
        ],
        correctIndex: 1,
        explanation: "EV represents the total cost to acquire the entire business, including assumption of debt and preferred stock. Market Cap is only the equity value.",
      },
      {
        id: "acc_42",
        question: "What does 'gross margin' measure?",
        options: [
          "Net income as a percentage of revenue",
          "The percentage of revenue remaining after deducting cost of goods sold",
          "Operating income as a percentage of revenue",
          "Revenue minus SG&A expenses",
        ],
        correctIndex: 1,
        explanation: "Gross Margin = (Revenue − COGS) / Revenue. It measures the core profitability of producing/delivering the product or service before overhead costs.",
      },
      {
        id: "acc_43",
        question: "What is a 'contingent liability' and how is it treated on the balance sheet?",
        options: [
          "A guaranteed future liability; always recorded on the balance sheet",
          "A potential obligation depending on an uncertain future event; recorded when probable and estimable",
          "A deferred tax liability",
          "An off-balance-sheet lease obligation",
        ],
        correctIndex: 1,
        explanation: "Contingent liabilities (e.g., lawsuits) are recognized as liabilities when it is probable they'll materialize and can be reasonably estimated. Otherwise, they're disclosed in footnotes.",
      },
      {
        id: "acc_44",
        question: "If a company writes down $50 of inventory, what happens to the income statement and balance sheet?",
        options: [
          "Revenue −$50; Assets unchanged",
          "COGS increases by $50 (reducing gross profit); Inventory decreases by $50 on balance sheet",
          "Cash decreases by $50; no income statement effect",
          "Net Income increases by $50",
        ],
        correctIndex: 1,
        explanation: "Inventory write-downs flow through COGS (or as a separate line), reducing gross profit and net income. The inventory asset decreases correspondingly.",
      },
      {
        id: "acc_45",
        question: "What is 'revenue recognition under ASC 606'?",
        options: [
          "Revenue is always recognized when cash is received",
          "Revenue is recognized when control of goods/services transfers to the customer, following a 5-step model",
          "Revenue is recognized when the contract is signed",
          "Revenue is recognized evenly over the fiscal year",
        ],
        correctIndex: 1,
        explanation: "ASC 606 introduced a 5-step framework: identify contract, identify performance obligations, determine transaction price, allocate price, recognize when obligations are satisfied.",
      },
      {
        id: "acc_46",
        question: "What is the cash conversion cycle (CCC) and what does a shorter CCC indicate?",
        options: [
          "CCC = DSO + DIO − DPO; a shorter CCC means less cash is tied up in operations",
          "CCC = Revenue / Cash; shorter means higher profitability",
          "CCC = Total Debt / Cash Flow; shorter means lower leverage",
          "CCC = Net Income × Asset Turnover; shorter means lower margins",
        ],
        correctIndex: 0,
        explanation: "CCC = Days Sales Outstanding + Days Inventory Outstanding − Days Payable Outstanding. A shorter CCC means the business collects cash faster relative to its obligations, improving liquidity.",
      },
      {
        id: "acc_47",
        question: "What is 'comprehensive income'?",
        options: [
          "The same as net income",
          "Net income plus other comprehensive income items (e.g., foreign currency translation, unrealized securities gains/losses)",
          "EBITDA adjusted for all non-recurring items",
          "Operating income before taxes",
        ],
        correctIndex: 1,
        explanation: "Comprehensive income includes net income plus OCI items that bypass the income statement but affect equity, like unrealized gains on AFS securities and pension adjustments.",
      },
      {
        id: "acc_48",
        question: "What is 'segment reporting' and why is it useful for analysts?",
        options: [
          "Reporting consolidated totals only",
          "Disclosing performance by business unit or geography, allowing analysts to value segments separately and identify hidden value or problems",
          "A required monthly report for regulators",
          "A reconciliation between GAAP and non-GAAP metrics",
        ],
        correctIndex: 1,
        explanation: "Segment reporting breaks down financials by division or region. Analysts use it to understand which parts of the business drive profitability and to apply segment-specific multiples.",
      },
      {
        id: "acc_49",
        question: "What is the equity method of accounting and when is it used?",
        options: [
          "Recording investments at fair market value; used for all equity investments",
          "Recording an investment proportionally in income and on the balance sheet; used when a company has significant influence (typically 20–50% ownership)",
          "Fully consolidating a subsidiary; used for majority-owned entities",
          "Recording investments at cost; used for minority passive investments",
        ],
        correctIndex: 1,
        explanation: "The equity method is applied when an investor can exercise significant influence but not control. The investor records its proportional share of the investee's net income.",
      },
      {
        id: "acc_50",
        question: "What is the difference between 'book value' and 'market value' of equity?",
        options: [
          "They are always equal for public companies",
          "Book value is shareholders' equity per the balance sheet (historical cost basis); market value is shares outstanding × current stock price",
          "Book value is higher than market value for growth companies",
          "Market value is used for tax reporting; book value is used for investor communications",
        ],
        correctIndex: 1,
        explanation: "Book value reflects cumulative accounting entries (historical cost). Market value reflects investors' forward-looking expectations of future earnings and is almost always different from book value.",
      },
    ],
  },
];
